[package]
name = "email_newsletter_service"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
tokio-macros = { version = "2.6.0" }
config = "0.15.18"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = "0.12.24"
#sqlx = "0.8"
sqlx-core = "0.8"
sqlx-postgres = "0.8"
serde = { version = "1", features = ["derive"] }
chrono = "0.4.42"
dotenv = "0.15"
uuid = { version = "1", features = ["v4"] }
log = "0.4.28"

[lib]
path = "src/lib.rs"

[[bin]]
name = "email_newsletter_service"
path = "src/main.rs"

[dependencies.sqlx]
version = "0.8"
default-features = false
features = [
    "runtime-tokio-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate"
]
